export enum ErrorCode {
	UNKNOWN = '',
	CARD_INVALID_CARD_TYPE = 'CARD_INVALID_CARD_TYPE',
	CHANGES_FORBIDDEN_IN_VERIFIED_ACCOUNT = 'CHANGES_FORBIDDEN_IN_VERIFIED_ACCOUNT',
	INVALID_HAULER_MISSING_PROPERTY = 'INVALID_HAULER_MISSING_PROPERTY',
	INVALID_REQUEST_MISSING_PROPERTY = 'INVALID_REQUEST_MISSING_PROPERTY',
	INVALID_PAYMENT_TOKEN = 'INVALID_PAYMENT_TOKEN',
	INVALID_REQUEST_AGE_RESTRICTION = 'INVALID_REQUEST_AGE_RESTRICTION',
	INVALID_REQUEST_EIN_COMPANY_ONLY = 'INVALID_REQUEST_EIN_COMPANY_ONLY',
	INVALID_REQUEST_INVALID_US_POSTAL_CODE = 'INVALID_REQUEST_INVALID_US_POSTAL_CODE',
	INVALID_SSN_TOKEN = 'INVALID_SSN_TOKEN',
	UNRECOGNIZED_STRIPE_ERROR = 'UNRECOGNIZED_STRIPE_ERROR'
}
