export enum AttachmentType {
    AVATAR_PICTURE = 'AVATAR_PICTURE',
    DRIVER_LICENSE_PICTURE_FRONT = 'DRIVERS_LICENSE_PICTURE_FRONT',
    DRIVER_LICENSE_PICTURE_BACK = 'DRIVERS_LICENSE_PICTURE_BACK',
    VEHICLE_PICTURE_A = 'VEHICLE_PICTURE_A',
    VEHICLE_PICTURE_B = 'VEHICLE_PICTURE_B',
    VEHICLE_PICTURE_C = 'VEHICLE_PICTURE_C',
    VEHICLE_PICTURE_D = 'VEHICLE_PICTURE_D'
}
