export enum HaulerAccountStatus {
    REGISTRATION_STARTED = 'REGISTRATION_STARTED',
    ON_WAITING_LIST = 'ON_WAITING_LIST',
    REVIEW = 'REVIEW',
    LOST = 'LOST',
    HAULER_ACTIVE = 'ACTIVE',
    HAULER_SUSPENDED = 'SUSPENDED'
}
