export enum HaulerAccountSubStatuses {
    SUBMITTED = 'SUBMITTED',
    STARTED = 'STARTED',
    INCOMPLETE_INFO = 'INCOMPLETE_INFO',
    NOT_QUALIFIED = 'NOT_QUALIFIED',
    NOT_INTEREST = 'NOT_INTEREST',
    BANKING_INFO_MISSING = 'BANKING_INFO_MISSING',
    INFO_CHANGED = 'INFO_CHANGED',
    MISSING_INFORMATION = 'MISSING_INFORMATION'
}
